### ISSUE TITLE
Data link invalid

### ISSUE THREAD

**Issue by wxlearncoding** [plantabrick/VINet#1]
Hello, I have two questions.

Your data link is invalid, Could you update it?
Which platform is your program built on, Linux or windows?

Looking forward to your reply. Thank you~

**Comment by plantabrick** [comment]
So sorry. The link I set up is long-term. But the Baidu SkyDrive banned the file. 
I need to recompress the dataset and upload it, which will take a while.
I write programs on Linux.
Although I didn't try, I think it can also works on windows.
If the dataset is uploaded, I will send you another email.
Thank you for telling me this problem.      






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wxlearncoding"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 中午11:06
收件人:&nbsp;"plantabrick/VINet"<VINet@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[plantabrick/VINet] Data link invalid (#1)




Hello, I have two questions.
 
Your data link is invalid, Could you update it?
 Which platform is your program built on, Linux or windows?
 
Looking forward to your reply. Thank you~

**Comment by wxlearncoding** [comment]
Thank you very much!

**Comment by plantabrick** [comment]
I uploaded the dataset again. In order to prevent being banned by Baidu disk, the password is added to the compressed file.
Compressed file password：vinet


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wxlearncoding"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 中午11:06
收件人:&nbsp;"plantabrick/VINet"<VINet@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[plantabrick/VINet] Data link invalid (#1)




Hello, I have two questions.
 
Your data link is invalid, Could you update it?
 Which platform is your program built on, Linux or windows?
 
Looking forward to your reply. Thank you~

**Comment by wxlearncoding** [comment]
Thanks. I have successfully downloaded the data.
