### ISSUE TITLE
Lack of main.py

### ISSUE THREAD

**Issue by wxlearncoding** [plantabrick/VINet#2]
Hello, I have a few more questions.

There is no main.py in your program. Could you upload it?

Have you published any relevant papers? I want to learn the principle.

What is the classification accuracy rate of benign and malignant?

Looking forward to your reply. Thank you~

**Comment by plantabrick** [comment]
Sorry, my "readme" is wrong.

we should run test.py instead of main.py
     
 
          
 In fact, the paper is still under review. So I am surprised that someone found this project.

For accuracy, you can try to run test.py. 


In fact, our network does not contribute to the accuracy of classification.
    
 
          
 The main contribution of this paper is visualization 
     

Thank you very much. Your email let me find out problem of the project.
 
     

 
     





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wxlearncoding"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 下午2:56
收件人:&nbsp;"plantabrick/VINet"<VINet@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[plantabrick/VINet] Lack of main.py (#2)




Hello, I have a few more questions.
 
There is no main.py in your program. Could you upload it?
 
Have you published any relevant papers? I want to learn the principle.
 
What is the classification accuracy rate of benign and malignant?
 
Looking forward to your reply. Thank you~

**Comment by wxlearncoding** [comment]
Thank you very much for your reply. Hope to see your paper in the future!
